# POST https://localhost:7001/api/weatherforecast
# content-Type: application/json

# {
#     "date": "5030-01-28T21:05:16.9191243-04:00",
#     "temperatureC": 0,
#     "temperatureF": 0,
#     "summary": "Omg amazing"
# }

# ------- TimeMiddleware
# GET https://localhost:7001/api/weatherforecast?time
# DELETE https://localhost:7001/api/weatherforecast/5
# GET https://localhost:7001/api/helloworld
# GET https://localhost:7001/api/helloworld/createdb


# ------ PROBANDO ENDPOINTS DE CATEGORIA

# GET https://localhost:7001/api/Categoria

# POST https://localhost:7001/api/Categoria
# content-type: application/json

# {
#     "nombre": "Actividad vacaciones",
#     "descripcion": "Planificar viajes",
#     "peso": 14
# }

# PUT https://localhost:7001/api/Categoria/3a82ce26-8edd-4c72-9b05-05872b781198
# content-type: application/json

# {
#     "nombre": "Actividades pendientes",
#     "descripcion": "Hacer tareas",
#     "peso": 20
# }

# PROBANDO ENDPOINTS DE TAREAS
#GET https://localhost:7001/api/Tareas

# POST https://localhost:7001/api/Tareas
# Content-Type: application/json

# {
#     "categoriaId": "3a82ce26-8edd-4c72-9b05-05872b781102",
#     "titulo": "Leer mis libros",
#     "descripcion": "Revisar cuales libros tengo pendientes y leerlos",
#     "prioridadTarea": 1,
#     "autor": "Mari"
# }

PUT https://localhost:7001/api/Tareas/f0de7f3b-50cf-4245-857e-7f13f13012e8
Content-Type: application/json

{
    "titulo": "Terminar de ver series",
    "descripcion": "Chequear las recomendadas y verlas en la noche",
    "prioridadTarea": 2,
    "autor": "Laura"
}